"""Standalone retarget self-check — run ``python3 -m multimodal_pipeline.retarget.selftest``.

Mirrors the package's self-check ethos (cf. real_ingest's world↔camera round-trip):
fast, dependency-light, asserts the kinematics and solver are correct so a broken
URDF parse or Jacobian is caught immediately. Exits non-zero on any failure.
"""

from __future__ import annotations

import sys

import numpy as np

from .optimize import kabsch_rotation, solve_hand_qpos
from .robot import RobotModel


def _check_fk_jacobian(model: RobotModel) -> list[str]:
    """Analytic palm-local Jacobian must match finite differences."""
    fails = []
    q = model.tree.midpoint()
    tips, J = model.fingertips_local_with_jac(q)
    eps = 1e-6
    Jfd = np.zeros_like(J)
    for hk, gk in enumerate(model.hand_idx):
        dp = q.copy(); dp[gk] += eps
        dm = q.copy(); dm[gk] -= eps
        Jfd[:, :, hk] = (model.fingertips_local(dp) - model.fingertips_local(dm)) / (2 * eps)
    err = float(np.abs(J - Jfd).max())
    if err > 1e-6:
        fails.append(f"{model.urdf_path.name}: FK Jacobian vs finite-diff = {err:.2e} (> 1e-6)")
    return fails


def _check_roundtrip(model: RobotModel, seed: int = 0) -> list[str]:
    """A reachable target (generated by FK of a random valid qpos) must be
    recovered to sub-mm fingertip error."""
    fails = []
    rng = np.random.default_rng(seed)
    lo, hi = model.hand_limits[:, 0], model.hand_limits[:, 1]
    worst = 0.0
    for _ in range(5):
        q_true = lo + (hi - lo) * rng.random(model.n_hand)
        full = model.tree.midpoint().copy(); full[model.hand_idx] = q_true
        target = model.fingertips_local(full)
        q_est = solve_hand_qpos(model, target, smooth_weight=0.0, n_iters=60)
        full_e = model.tree.midpoint().copy(); full_e[model.hand_idx] = q_est
        err = float(np.max(np.linalg.norm(model.fingertips_local(full_e) - target, axis=1)) * 1000)
        worst = max(worst, err)
        if not np.all((q_est >= lo - 1e-6) & (q_est <= hi + 1e-6)):
            fails.append(f"{model.urdf_path.name}: solved qpos violates joint limits")
    if worst > 1.0:
        fails.append(f"{model.urdf_path.name}: roundtrip fingertip err {worst:.3f} mm (> 1 mm)")
    return fails


def main() -> int:
    fails: list[str] = []

    # Kabsch identity sanity.
    A = np.random.default_rng(0).random((5, 3))
    if np.abs(kabsch_rotation(A, A) - np.eye(3)).max() > 1e-9:
        fails.append("kabsch(A,A) != I")

    for side in ("left", "right"):
        model = RobotModel(side)
        if model.dof != 20 or model.n_hand != 20:
            fails.append(f"{side}: expected 20 hand DOF, got dof={model.dof} hand={model.n_hand}")
        fails += _check_fk_jacobian(model)
        fails += _check_roundtrip(model)
        print(f"  {side}: dof={model.dof} hand={model.n_hand} arm={model.n_arm} "
              f"robot_span={model._robot_span*100:.1f}cm  OK")

    if fails:
        print("\nRETARGET SELF-CHECK FAILED:")
        for f in fails:
            print(f"  ✗ {f}")
        return 1
    print("\nRETARGET SELF-CHECK PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
