"""Generate a SYNTHETIC placeholder arm+hand URDF for pipeline validation.

The real WH120+ARM model (20 hand + 3 arm joints ``*_arm_joint1/2``,
``*_palm_joint`` = 23 DOF) lives on the ``wh120_arm_mujoco`` branch and is not
on this box. To validate the full arm→hand retarget chain *before* it arrives,
this module grafts three revolute arm joints (with PLACEHOLDER geometry) onto
the vendored 20-DOF hand URDF, producing a 23-DOF ``*_synthetic.urdf``.

IMPORTANT — this is a *synthetic* model: the arm link lengths / axes are an
honest guess, NOT the real Wuji arm. Joint angles solved against it are correct
*for this placeholder*, and exist only to exercise the IK + column-writing
pipeline. Swap in the real ``dual_arm.urdf`` and everything downstream is
unchanged. Files are named ``*_synthetic.urdf`` and carry a header comment so
they can never be mistaken for the real model.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

# Placeholder arm geometry (metres / radians). Two "shoulder" joints + one
# "wrist" joint, ~0.53 m reach — enough to exercise under-actuated 3-DOF IK.
_ARM = [
    # (joint_suffix, axis, child_link, origin_xyz, limit). Two orthogonal
    # "shoulder" axes (pitch about y, roll about x) so the 3 DOF sweep a sphere
    # patch instead of degenerating; one "wrist" pitch. PLACEHOLDER geometry.
    ("arm_joint1", "0 1 0", "arm_link1", "0 0 0",      (-1.5708, 1.5708)),
    ("arm_joint2", "1 0 0", "arm_link2", "0 0 -0.28",  (-1.5708, 1.5708)),
    ("palm_joint", "0 1 0", "palm_link", "0 0 -0.25",  (-1.5708, 1.5708)),
]


def build_synthetic_arm_urdf(hand_urdf: Path, side: str, out_path: Path) -> Path:
    """Graft a 3-DOF placeholder arm before ``{side}_palm_link`` of a hand URDF.

    The hand subtree is preserved verbatim; we prepend ``base_link`` →
    arm_joint1 → arm_joint2 → palm_joint → (existing palm_link). Result is a
    23-DOF serial chain rooted at ``base_link``.
    """
    tree = ET.parse(hand_urdf)
    robot = tree.getroot()
    palm = f"{side}_palm_link"
    if not any(l.get("name") == palm for l in robot.findall("link")):
        raise ValueError(f"{hand_urdf} has no link {palm}")

    # New links: base + two arm links (palm_link already exists in the hand URDF).
    new_links = ["base_link", f"{side}_arm_link1", f"{side}_arm_link2"]
    link_els = [ET.Element("link", {"name": n}) for n in new_links]

    # New joints: base→arm1→arm2→palm. Insert them so they appear before the
    # hand joints in document order (→ qpos indices 0,1,2 are the arm).
    parent = "base_link"
    joint_els = []
    for suffix, axis, child, xyz, (lo, hi) in _ARM:
        child_link = f"{side}_{child}" if child != "palm_link" else palm
        j = ET.Element("joint", {"name": f"{side}_{suffix}", "type": "revolute"})
        ET.SubElement(j, "origin", {"xyz": xyz, "rpy": "0 0 0"})
        ET.SubElement(j, "parent", {"link": parent})
        ET.SubElement(j, "child", {"link": child_link})
        ET.SubElement(j, "axis", {"xyz": axis})
        ET.SubElement(j, "limit", {"lower": str(lo), "upper": str(hi),
                                   "effort": "10", "velocity": "3"})
        joint_els.append(j)
        parent = child_link

    # Prepend new links + joints (order: new links first, new joints first).
    for el in reversed(link_els):
        robot.insert(0, el)
    # joints after links but before existing hand joints
    existing_joint_idx = next(
        (i for i, c in enumerate(list(robot)) if c.tag == "joint"), len(list(robot)))
    for off, j in enumerate(joint_els):
        robot.insert(existing_joint_idx + off, j)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = ("<!-- SYNTHETIC PLACEHOLDER arm geometry — NOT the real Wuji arm. "
              "Generated by retarget/synth_arm.py for pipeline validation only. "
              "Replace with the real dual_arm.urdf when available. -->\n")
    xml = ET.tostring(robot, encoding="unicode")
    out_path.write_text(header + xml, encoding="utf-8")
    return out_path


def ensure_synthetic_pair(assets_dir: Path) -> dict[str, Path]:
    """Build left/right synthetic arm URDFs from the vendored hand URDFs."""
    out = {}
    for side in ("left", "right"):
        hand = assets_dir / f"{side}.urdf"
        out[side] = build_synthetic_arm_urdf(hand, side, assets_dir / f"{side}_arm_synthetic.urdf")
    return out


if __name__ == "__main__":
    d = Path(__file__).resolve().parent / "assets" / "wuji"
    for side, p in ensure_synthetic_pair(d).items():
        print(f"  {side}: {p}")
